<a href="https://colab.research.google.com/github/swapnilchavan0707/SwapMLDev/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Pandas -- (Python for Data Analysis)**

In [ ]:
import pandas as pd
a1 = pd.Series(1)
a1

0    1
dtype: int64

In [ ]:
a1 = pd.Series([1, 2])
a1

0    1
1    2
dtype: int64

In [ ]:
a1 = pd.Series([[1, 2]])
a1

0    [1, 2]
dtype: object

In [ ]:
a1 = pd.Series([[[[1, 2, 3]]]])
a1

0    [[[1, 2, 3]]]
dtype: object

In [ ]:
a1.ndim

1

In [ ]:
a1.size

1

In [ ]:
a2 = pd.DataFrame([[1, 2, 3, 4]])
a2

   0  1  2  3
0  1  2  3  4

In [ ]:
a2.ndim

2

### **Different ways of creating DataFrame**

In [ ]:
import numpy as np
a1 = np.array([1, 2, 3, 4])
a1

array([1, 2, 3, 4])

In [ ]:
a2 = pd.DataFrame(a1)
a2

   0
0  1
1  2
2  3
3  4

In [ ]:
a1 = {" Location " :  ['Mumbai', 'Pune', 'Thane'], "Grade " : ['A+', 'O+', 'O']}
a1

{' Location ': ['Mumbai', 'Pune', 'Thane'], 'Grade ': ['A+', 'O+', 'O']}

In [ ]:
a2 = pd.DataFrame(a1)
a2

   Location  Grade
0     Mumbai     A+
1       Pune     O+
2      Thane      O

In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
a2[" Location "][0] = "Bombay"

In [ ]:
a2[" Location "][0] = "Mumbai"

In [ ]:
a1 = pd.DataFrame({"a2":[11, 22, 33]})
a1

   a2
0  11
1  22
2  33

In [ ]:
a3 = pd.concat([a1, a2], axis = 1)
a3

   a2  Location  Grade
0  11     Mumbai     A+
1  22       Pune     O+
2  33      Thane      O

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("Fitness_trackers.csv")
df.head()

,Brand Name,Device Type,Model Name,Color,Selling Price,Original Price,Display,Rating (Out of 5),Strap Material,Average Battery Life (in days),Reviews
0,Xiaomi,FitnessBand,Smart Band 5,Black,"2,499","2,999",AMOLED Display,4.1,Thermoplastic polyurethane,14,NaN
1,Xiaomi,FitnessBand,Smart Band 4,Black,"2,099","2,499",AMOLED Display,4.2,Thermoplastic polyurethane,14,NaN
2,Xiaomi,FitnessBand,HMSH01GE,Black,"1,722","2,099",LCD Display,3.5,Leather,14,NaN
3,Xiaomi,FitnessBand,Smart Band 5,Black,"2,469","2,999",AMOLED Display,4.1,Thermoplastic polyurethane,14,NaN
4,Xiaomi,FitnessBand,Band 3,Black,"1,799","2,199",OLED Display,4.3,Plastic,7,NaN

In [ ]:
df.shape

(565, 11)

In [ ]:
df.tail()

,Brand Name,Device Type,Model Name,Color,Selling Price,Original Price,Display,Rating (Out of 5),Strap Material,Average Battery Life (in days),Reviews
560,Huawei,Smartwatch,Watch 36456,Black,"55,000","55,000",AMOLED Display,4.1,Silicone,14,NaN
561,Huawei,Smartwatch,GT Fortuna-B19S Sport,Black,"13,990","20,990",AMOLED Display,4.1,Elastomer,14,NaN
562,GOQii,FitnessBand,HR,Black,"1,999","1,999",OLED Display,3.8,Silicone,7,NaN
563,GOQii,FitnessBand,Vital,Black,"3,499","3,499",OLED Display,3.7,Thermoplastic polyurethane,7,NaN
564,FOSSIL,Smartwatch,Gen 5E,"Grey, Multicolor","18,495","18,495",AMOLED Display,4.2,Stainless Steel,1,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 565 entries, 0 to 564
Data columns (total 11 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Brand Name                      565 non-null    object
 1   Device Type                     565 non-null    object
 2   Model Name                      565 non-null    object
 3   Color                           565 non-null    object
 4   Selling Price                   565 non-null    object
 5   Original Price                  565 non-null    object
 6   Display                         565 non-null    object
 7   Rating (Out of 5)               514 non-null    float64
 8   Strap Material                  565 non-null    object
 9   Average Battery Life (in days)  565 non-null    int64
 10  Reviews                         78 non-null     object
dtypes: float64(1), int64(1), object(9)
memory usage: 48.7+ KB

In [ ]:
# non-null (not empty)

In [ ]:
df.describe()

       Rating (Out of 5)  Average Battery Life (in days)
count         514.000000                      565.000000
mean            4.229961                        9.026549
std             0.390827                        7.868670
min             2.000000                        1.000000
25%             4.025000                        2.000000
50%             4.300000                        7.000000
75%             4.500000                       14.000000
max             5.000000                       45.000000

In [ ]:
df.describe(include = "object")

,Brand Name,Device Type,Model Name,Color,Selling Price,Original Price,Display,Strap Material,Reviews
count,565,565,565,565,565,565,565,565,78
unique,20,2,384,146,244,178,7,12,46
top,FOSSIL,Smartwatch,Charge 2,Black,"8,995","11,995",AMOLED Display,Silicone,489
freq,133,490,8,193,16,19,355,232,8

In [ ]:
df.describe(exclude = "object")

       Rating (Out of 5)  Average Battery Life (in days)
count         514.000000                      565.000000
mean            4.229961                        9.026549
std             0.390827                        7.868670
min             2.000000                        1.000000
25%             4.025000                        2.000000
50%             4.300000                        7.000000
75%             4.500000                       14.000000
max             5.000000                       45.000000

In [ ]:
import seaborn as sns
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [ ]:
sns.load_dataset('titanic')
df.head()

,Brand Name,Device Type,Model Name,Color,Selling Price,Original Price,Display,Rating (Out of 5),Strap Material,Average Battery Life (in days),Reviews
0,Xiaomi,FitnessBand,Smart Band 5,Black,"2,499","2,999",AMOLED Display,4.1,Thermoplastic polyurethane,14,NaN
1,Xiaomi,FitnessBand,Smart Band 4,Black,"2,099","2,499",AMOLED Display,4.2,Thermoplastic polyurethane,14,NaN
2,Xiaomi,FitnessBand,HMSH01GE,Black,"1,722","2,099",LCD Display,3.5,Leather,14,NaN
3,Xiaomi,FitnessBand,Smart Band 5,Black,"2,469","2,999",AMOLED Display,4.1,Thermoplastic polyurethane,14,NaN
4,Xiaomi,FitnessBand,Band 3,Black,"1,799","2,199",OLED Display,4.3,Plastic,7,NaN

In [ ]:
df = sns.load_dataset('taxis')
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [ ]:
df = sns.load_dataset('tips')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
df = sns.load_dataset('flights')
df

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [ ]:
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

### **Treatment of Missing Values**

In [ ]:
df.isnull()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
887,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False
889,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False

In [ ]:
del df["deck"]

In [ ]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
who            0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64

In [ ]:
df.isnull().sum().sum() #isna()

4

In [ ]:
df["age"].mean()

29.36158249158249

In [ ]:
df["age"].median()

28.0

In [ ]:
df["age"].fillna(28.0) # Temporay function

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [ ]:
df["age"].isnull().sum()

0

In [ ]:
df["age"] = df["age"].fillna(28.0)
df["age"].isnull().sum()

0

In [ ]:
df.dropna(inplace = True)

In [ ]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [ ]:
df.duplicated().sum()

116

In [ ]:
df.drop_duplicates(inplace = True)

In [ ]:
df.duplicated().sum()

0

In [ ]:
df["survived"].head()

0    0
1    1
2    1
3    1
4    0
Name: survived, dtype: int64